name: Java CI with Maven

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '15'
        distribution: 'adopt'
        cache: maven
    - name: Step 1 - Build with Maven
      run: mvn -B package --file pom.xml
      
    - name: Step 2 - Run the Maven verify phase
      run: mvn --batch-mode --update-snapshots verify
      
    - name: Step 3 - Running tests
      run: mvn --test
